name = "discord-cdn-proxy"
main = "src/index.ts"
compatibility_date = "2026-04-17"
preview_urls = false

# Uncomment below if you want to use specific to your website routing.
# Make sure to update useapi.net to desired values.
# routes = [ { pattern = "demo.useapi.net/discord-cdn-proxy/*", zone_name = "useapi.net" } ]

# Uncomment below if you want to use kv namespace for caching.
[[kv_namespaces]]
binding = "KV"
id = "4d2eb4bc36fd4facb40f8f3307a14552"
